version: '3.4'

volumes:
  tpc-h-data:

services:
  db:
    image: postgres:17.5
    restart: always
    container_name: tpc_h
    ports:
      - 54321:5432
    environment:
      - PGDATA=/data
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - tpc-h-data:/data