coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
query.max-memory=2GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
discovery-server.enabled=true
discovery.uri=http://coordinator:8080

# History-Based Optimizer (HBO)
optimizer.use-history-based-plan-statistics=true
optimizer.track-history-based-plan-statistics=true
optimizer.history-based-optimizer-timeout=60s

# Recommended alongside HBO
optimizer.join-reordering-strategy=AUTOMATIC
optimizer.max-reordered-joins=9

optimizer.enforce-timeout-for-hbo-query-registration=true
optimizer.history-based-optimizer-estimate-size-using-variables=true
optimizer.log-plans-used-in-history-based-optimizer=true
optimizer.retry-query-with-history-based-optimization=true
optimizer.track-history-based-plan-statistics=true
optimizer.use-partial-aggregation-history=true