com.facebook.presto=INFO
com.facebook.presto.cost.HistoryBasedPlanStatisticsCalculator=DEBUG
com.facebook.presto.cost.HistoryBasedStatisticsCacheManager=DEBUG
com.facebook.presto.sql.planner.HistoryBasedOptimizationContext=DEBUG
