connector.name=postgresql
connection-url=jdbc:postgresql://ep-restless-bread-agy58ubz-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb
connection-user=neondb_owner
connection-password=npg_ONaIJQ4Usdy5